# Generated by Django 4.2.3 on 2023-08-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stuent',
            new_name='Student',
        ),
    ]
